services:
  app:
    build:
      context: .
    ports:
      - '3001:3000'
    read_only: true
    volumes:
      - '/tmp:/tmp'
      - '../../configs/image-service:/sandbox'
      - './metadata:/metadata'
      # - './static:/app/static'
